### PR TITLE
Add support for leagueId so we can retrieve data from other leagues

### PR DESCRIPTION
**Pull request by BrayanMnz**
Add support for leagueId so we can retrieve data from a league different from MLB.

### CODE REVIEW

**Comment by BrayanMnz** [comment]
FYI @toddrob99

**Comment by BrayanMnz** [comment]
Hi, @toddrob99 could you merge this?

**Comment by toddrob99** [comment]
@BrayanMnz, can you give me an example of how you are looking to use this? The `sportId` parameter is already there, and that's the one that lets you retrieve the schedule outside MLB (for example, AAA):

```
> aaa_schedule = statsapi.schedule(date="2024-05-01", sportId=11)
> print(aaa_schedule[-1])

2024-05-01 - Reno Aces @ Las Vegas Aviators (Scheduled)
```

The `leagueId` parameter would allow you to filter the results to one league within the given sport (for example, only retrieve American League schedule for sportId=1/MLB), but the current functionality does allow retrieving data for any league as far as I can tell.

**Comment by BrayanMnz** [comment]
Hi, @toddrob99 do you have a dictionary about all the available sportId?

**Comment by toddrob99** [comment]
Included in v1.7.1

**Pull request merged**
